apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::411370101013:role/eksctl-depProjct-nodegroup-ng-81b-NodeInstanceRole-AFF9JZT94QK6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::411370101013:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-27T15:40:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "791"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d79599c8-d1d8-471b-b708-61e89ef66a21
